### ISSUE TITLE
Registrar em foto ou vídeo: armários principal e secundário

### ISSUE THREAD

**Issue by ghost** [boidacarapreta/cab20202#28]
Baseado em #12 e #18, gravar filmar ou fotos do câmpus São José:
- [x] Armário principal
- [x] Armários secundários

**Comment by boidacarapreta** [comment]
A tarefa não foi executada neste repositório. De qualquer forma, será marcada como concluída para o andamento da disciplina.

**Comment by ghost** [comment]
Vídeo publicado no Youtube: https://www.youtube.com/watch?v=LQ2G0_SUIgQ
