### ISSUE TITLE
Gerar a primeira versão do jogo

### ISSUE THREAD

**Issue by ghost** [boidacarapreta/cab20202#5]
Exportar em HTML para leitura.

**Comment by boidacarapreta** [comment]
Assistido ao vídeo, lido o livro e assinado o canal.

**Comment by ghost** [comment]
Fechei por engano a tarefa...

**Comment by ghost** [comment]
Configurado o GitHub Pages para apontar para o ramo principal, `main`, e pasta raiz, `/`, onde está o meu arquivo exportado pelo Twine, `index.html`:

![Captura de Tela 2020-12-19 às 01 04 26](https://user-images.githubusercontent.com/726005/102680356-3846dc80-4196-11eb-8204-8a86bcb4480b.png)

**Comment by ghost** [comment]
URL para ler: [https://boidacarapreta.github.io/cab20202](https://boidacarapreta.github.io/cab20202).

**Comment by netindev** [comment]
apesar do issue está closed, irei repassar aqui, a primeira versão "buildada" do game em ação.

https://github.com/darkzone2/egg-clicker/blob/main/Capture.PNG

**Comment by Bruno-O20** [comment]
Boa noite prof, como a aba de comentários não aceita .html, compactamos para Zip/Winrar e possibilita mostrar aqui o início do que foi feito.

[The.really.hot.hot.dog.zip](https://github.com/boidacarapreta/cab20202/files/5727502/The.really.hot.hot.dog.zip)

**Comment by ghost** [comment]
> Boa noite prof, como a aba de comentários não aceita .html, compactamos para Zip/Winrar e possibilita mostrar aqui o início do que foi feito.
> 
> [The.really.hot.hot.dog.zip](https://github.com/boidacarapreta/cab20202/files/5727502/The.really.hot.hot.dog.zip)

@Bruno-O20 visto! Está bom o começo. Pode colocar o arquivo no repositório como `index.html` que será criado com o GitHub Pages, conforme a tarefa.
