### ISSUE TITLE
[Exercício] Converter primeiro nome em códigos de linhas

### ISSUE THREAD

**Issue by ghost** [boidacarapreta/cab20202#6]
Como exercício da disciplina, pegar o primeiro nome e:
1. Converter em números decimais tendo como referência a [tabela ASCII](https://pt.wikipedia.org/wiki/ASCII).
1. Converter cada número decimal em uma cadeia de 8 bits em binário.
1. Desenhar, seja no papel ou outra ferramenta ([planilha](https://docs.google.com/spreadsheets/d/18sqySQKKB5BqWNXx7h07yztt_3TLdeWd23AuQtH23cg/edit?usp=sharing), por exemplo), em 3 códigos de linha:
   1. NRZ
   1. MLT-3
   1. PAM5

**Comment by Jessica-ps** [comment]
https://drive.google.com/file/d/1T_1axHH3GGdVmjfY5qJ1r5X2Fb2rrP8y/view
Trabalho da tabela Ascii

**Comment by Ernzen1** [comment]
Documento e planilha da atividade em sequência:
https://docs.google.com/document/d/1UIMow04xeajFKMRZohrvBhFspuY2i1aSe698fRee_cs/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1VdFCIj2YVqEFdIcLUOI_QergRmiPJLHGzPFySBwSMLQ/edit?usp=sharing

[Código de linha Cabeamento.docx](https://github.com/boidacarapreta/cab20202/files/5699865/Codigo.de.linha.Cabeamento.docx)
[Código de linha cabeamento.xlsx](https://github.com/boidacarapreta/cab20202/files/5699866/Codigo.de.linha.cabeamento.xlsx)

**Comment by 25Violet** [comment]
[codigos.xlsx](https://github.com/boidacarapreta/cab20202/files/5699878/codigos.xlsx)
[codigolin.pdf](https://github.com/boidacarapreta/cab20202/files/5699880/codigolin.pdf)

**Comment by Ernzen1** [comment]
Aluno: Guilherme Ernzen Marçal 
Documento e planilha da atividade em sequência:
[Código de linha Cabeamento.docx](https://github.com/boidacarapreta/cab20202/files/5699882/Codigo.de.linha.Cabeamento.docx)
[Código de linha cabeamento.xlsx](https://github.com/boidacarapreta/cab20202/files/5699883/Codigo.de.linha.cabeamento.xlsx)

**Comment by Bruno-O20** [comment]
~Bruno de Oliveira

[AtividadeNome.pdf](https://github.com/boidacarapreta/cab20202/files/5700058/AtividadeNome.pdf)
[BrunoCodificado.xlsx](https://github.com/boidacarapreta/cab20202/files/5700059/BrunoCodificado.xlsx)

*Refeito*

**Comment by ghost** [comment]
> Aluno: Guilherme Ernzen Marçal
> Documento e planilha da atividade em sequência:
> [Código de linha Cabeamento.docx](https://github.com/boidacarapreta/cab20202/files/5699882/Codigo.de.linha.Cabeamento.docx)
> [Código de linha cabeamento.xlsx](https://github.com/boidacarapreta/cab20202/files/5699883/Codigo.de.linha.cabeamento.xlsx)

@Ernzen1 a conversão de nome para ASCII (converter letra a letra) está ok. Porém, a conversão de decimal-binário não: cada letra na tabela ASCII pode ser convertida diretamente para uma cadeia de 8 bits em binário. Assim, o teu nome, "Guilherme", terá no máximo 9 agrupamentos de 8 bits, ou 8 bytes. Vi que deu trabalho fazer a planilha, mas é preciso refazê-la, já que os valores são diferentes.

**Comment by ghost** [comment]
> ~Bruno de Oliveira
> 
> [AtividadeNome.pdf](https://github.com/boidacarapreta/cab20202/files/5699956/AtividadeNome.pdf)
> [BrunoCodificado.xlsx](https://github.com/boidacarapreta/cab20202/files/5699957/BrunoCodificado.xlsx)

Infelizmente, @Bruno-O20, o mesmo se aplica ao teu caso: cada letra leva a um decimal, que por sua vez a um byte. É preciso refazer a conversão decimal-binário e, por consequência, os códigos de linhas.

**Comment by netindev** [comment]
José Neto.

[Cab.pdf](https://github.com/boidacarapreta/cab20202/files/5700036/Cab.pdf)
[Cab.xlsx](https://github.com/boidacarapreta/cab20202/files/5700037/Cab.xlsx)

**Comment by ghost** [comment]
A [planilha de exemplo](https://docs.google.com/spreadsheets/d/18sqySQKKB5BqWNXx7h07yztt_3TLdeWd23AuQtH23cg/edit?usp=sharing) foi preenchida com o primeiro nome, "Ederson".

**Comment by lasscampos** [comment]
Larissa de Campos da Silva 
https://docs.google.com/spreadsheets/d/1-LkFgW3h2nwBuytxqsowljJUONA28-a3HiFks90zEaI/edit?ts=5fdac055#gid=0

Refeito

**Comment by Fernandaalcione** [comment]
Fernanda Alcionê de Souza
https://docs.google.com/spreadsheets/d/1LERtropmiORT0ToNhJGwiS7AoDiVE33YYF_yZMvNCa0/edit#gid=0

**Comment by Ernzen1** [comment]
Atualizado.

[Código de linha Cabeamento.docx](https://github.com/boidacarapreta/cab20202/files/5705990/Codigo.de.linha.Cabeamento.docx)
[Código de linha cabeamento.xlsx](https://github.com/boidacarapreta/cab20202/files/5705991/Codigo.de.linha.cabeamento.xlsx)

**Comment by tcatarina** [comment]
(Atualizado)
Thiago Barbieri
[codigolin2.pdf](https://github.com/boidacarapreta/cab20202/files/5706235/codigolin2.pdf)
[codigos.xlsx](https://github.com/boidacarapreta/cab20202/files/5706237/codigos.xlsx)

**Comment by ghost** [comment]
> Larissa de Campos da Silva
> https://docs.google.com/spreadsheets/d/1-LkFgW3h2nwBuytxqsowljJUONA28-a3HiFks90zEaI/edit#gid=0
@lasscampos Solicitei acesso ao arquivo no  GDrive...

**Comment by ghost** [comment]
> Fernanda Alcionê de Souza
> https://docs.google.com/spreadsheets/d/1LERtropmiORT0ToNhJGwiS7AoDiVE33YYF_yZMvNCa0/edit#gid=0

@Fernandaalcione a conversão para ASCII está ok, assim como de decimal para binário. Porém, a partir do bit 6 da letra "d", coluna BD da planilha, a onda deveria seguir para nível de tensão inferior em MLT-3, não superior - para atender a senoidal. Códigos NRZ e PAM5 estão OK.

**Comment by ghost** [comment]
@Ernzen1 o teu caso foi semelhante ao de @@Fernandaalcione. No primeiro byte, a onda começa em tensão em nível baixo de tensão, e nos próximos bits em 1 vão para zero ou voltam para nível inferior, quando deveria ir para superior. Na segunda letra, no código PAM5 o primeiro par de bits está vazio. A partir da segunda letra ou byte, com os espaços em branco não consigo mais discriminar os bytes, já que são espaços intermitentes nos códigos de linha. A partir deste ponto, não foi mais possível corrigir.

**Comment by ghost** [comment]
> (Atualizado)
> Thiago Barbieri
> [codigolin2.pdf](https://github.com/boidacarapreta/cab20202/files/5706235/codigolin2.pdf)
> [codigos.xlsx](https://github.com/boidacarapreta/cab20202/files/5706237/codigos.xlsx)

@Barbyie, nos três códigos de linhas os valores não correspondem aos valores binários. Em NRZ, 1 é nível alto de tensão, enquanto que 0 é baixo, o que não ocorre no teu exercício. Em MLT-3, a onda se comporta de forma senoidal com alteração de nível com 1 e permanência com 0. Em PAM5, os pares são dispostos entre os 4 níveis de tensão, conforme as 4 possibilidades de valores com 2 bits (00, 01, 10 e 11).

**Comment by talita3286** [comment]
[Convertendo primeiro nome em códigos de linhas (Talita).pdf](https://github.com/boidacarapreta/cab20202/files/5716736/Convertendo.primeiro.nome.em.codigos.de.linhas.Talita.pdf)

**Comment by ghost** [comment]
> Convertendo primeiro nome em códigos de linhas (Talita).pdf

@talita3286 perfeito! Vou adicionar a lista de tarefas entregues.

**Comment by Jader-T** [comment]
Jader Theisges

[Conversão_Cab - Jader.xlsx](https://github.com/boidacarapreta/cab20202/files/5721560/Conversao_Cab.-.Jader.xlsx)
[Cab_Jader.pdf](https://github.com/boidacarapreta/cab20202/files/5721558/Cab_Jader.pdf)

**Comment by BigHouse29** [comment]
Gustavo
[pastilha nome ASCII.xlsx](https://github.com/boidacarapreta/cab20202/files/5721561/pastilha.nome.ASCII.xlsx)
[Conversor nome.pdf](https://github.com/boidacarapreta/cab20202/files/5721564/Conversor.nome.pdf)

**Comment by akyua** [comment]
Gabriel Henrique da Silveira

[Atividade ASCII.pdf](https://github.com/boidacarapreta/cab20202/files/5721628/Atividade.ASCII.pdf)
[Atividade ASCII.xlsx](https://github.com/boidacarapreta/cab20202/files/5721629/Atividade.ASCII.xlsx)

**Comment by tcatarina** [comment]
Refeito novamente

[codigos.xlsx](https://github.com/boidacarapreta/cab20202/files/5727513/codigos.xlsx)

**Comment by Ernzen1** [comment]
[Código de linha cabeamento.xlsx](https://github.com/boidacarapreta/cab20202/files/5731999/Codigo.de.linha.cabeamento.xlsx)

**Comment by Ernzen1** [comment]
Refeito

**Comment by Ernzen1** [comment]
Refeito

[Código de linha cabeamento  Guilherme Ernzen.xlsx](https://github.com/boidacarapreta/cab20202/files/5732003/Codigo.de.linha.cabeamento.Guilherme.Ernzen.xlsx)

**Comment by ghost** [comment]
> Refeito
> 
> [Código de linha cabeamento Guilherme Ernzen.xlsx](https://github.com/boidacarapreta/cab20202/files/5732003/Codigo.de.linha.cabeamento.Guilherme.Ernzen.xlsx)

@Ernzen1 o arquivo enviado por último é praticamente o mesmo do envio anterior. Li novamente, e entendi o que foi feito: em PAM5, há um espaçamento. A primeira vista, parece estar errado, mas o que acontece é o deslocamento dos bits para o lado. Tarefa entregue.
